name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://shop.azisasmara.my.id/
        # File akan otomatis tersimpan di sitemap.xml

    - name: Commit Sitemap
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # Cek apakah file berubah
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Update sitemap via Cicirello Action"
          git push
        else
          echo "No changes to commit"
        fi
